#cloud-config
autoinstall:
  version: 1
  identity:
    hostname: ubuntu
    username: dula
    password: "$6$5IVHiePAeuiSTTsS$T48hGc7rNVYRjKX2dRvpQnamtUkeb.ejTEVho4Xss381f4hTxo.AvHuWvUmjl2kmtu0PRI5jvU1JZKV0boUgO1"
  packages:
    - ufw
    - unattended-upgrades
    - aide
  storage:
    config:
      # Define the target disk using the largest available device.
      - ptable: gpt
        type: disk
        id: nvme0n1
        wipe: all
        match:
          size: largest

      # Create a dedicated /boot partition (unencrypted) of 512MiB.
      - device: nvme0n1
        size: 512MiB
        type: partition
        id: boot_partition
      - device: boot_partition
        filesystem: ext4
        mount: /boot

      # Allocate the remainder of the disk to LVM.
      - device: nvme0n1
        type: partition
        id: lvm_partition
        # This partition will be used as the physical volume for LVM after encryption.

      # Encrypt the LVM partition with LUKS using the AES-XTS cipher.
      - id: crypt_lvmpv
        type: crypt
        cipher: aes-xts-plain64
        key: "your-encryption-key"  # Replace with a secure key or secure retrieval method.
        device: lvm_partition

      # Create an LVM volume group from the encrypted physical volume.
      - id: lvm_group
        type: lvm_volgroup
        devices: [ crypt_lvmpv ]

      # Create Logical Volumes for a hardened desktop layout.
      # The percentages here sum to 100% of the available LVM space.
      
      # /home is allocated 35% of the space.
      - id: home_lv
        type: lvm_partition
        volgroup: lvm_group
        size: 35%
      - device: home_lv
        filesystem: ext4
        mount: /home

      # /tmp is allocated 5%, mounted with restrictions to prevent unintended execution.
      - id: tmp_lv
        type: lvm_partition
        volgroup: lvm_group
        size: 5%
      - device: tmp_lv
        filesystem: ext4
        mount: /tmp
        mount_options: [nosuid, nodev, noexec]

      # The root (/) partition gets 30%.
      - id: root_lv
        type: lvm_partition
        volgroup: lvm_group
        size: 30%
      - device: root_lv
        filesystem: ext4
        mount: /
        mount_options: [defaults]

      # /var is allocated 10%; keeping system variable data separate.
      - id: var_lv
        type: lvm_partition
        volgroup: lvm_group
        size: 10%
      - device: var_lv
        filesystem: ext4
        mount: /var

      # /var/log is allocated 10% and mounted with strict options to prevent execution.
      - id: var_log_lv
        type: lvm_partition
        volgroup: lvm_group
        size: 10%
      - device: var_log_lv
        filesystem: ext4
        mount: /var/log
        mount_options: [nosuid, nodev, noexec]

      # /var/log/audit is allocated 5% for audit logs.
      - id: var_log_audit_lv
        type: lvm_partition
        volgroup: lvm_group
        size: 5%
      - device: var_log_audit_lv
        filesystem: ext4
        mount: /var/log/audit
        mount_options: [nosuid, nodev, noexec]
      
      # /var/tmp is allocated 5%, separating persistent temporary files.
      - id: var_tmp_lv
        type: lvm_partition
        volgroup: lvm_group
        size: 5%
      - device: var_tmp_lv
        filesystem: ext4
        mount: /var/tmp
        mount_options: [nosuid, nodev, noexec]

  late-commands:
    # Update package indices to ensure the latest packages are installed.
    - curtin in-target --target=/target apt-get update
    # Install ufw, unattended-upgrades, and aide for enhanced security.
    - curtin in-target --target=/target apt-get -y install ufw unattended-upgrades aide
    # Enable the firewall.
    - curtin in-target --target=/target ufw enable
    # Enable automatic security updates.
    - curtin in-target --target=/target systemctl enable unattended-upgrades
    # Remove any insecure sudoers settings (e.g., inadvertent NOPASSWD rules).
    - curtin in-target --target=/target bash -c "sed -i 's/.*NOPASSWD.*/# &/' /etc/sudoers"
